apiVersion: v1
kind: Service
metadata:
  name: besu-service
  namespace: besu
spec:
  type: LoadBalancer  # Change from ClusterIP
  selector:
    app: besu
  ports:
    - name: json-rpc
      port: 8545
      targetPort: 8545
      protocol: TCP
    - name: websocket
      port: 8546
      targetPort: 8546
      protocol: TCP
    - name: p2p
      port: 30303
      targetPort: 30303
      protocol: TCP