apiVersion: v1
kind: Service
metadata:
  name: besu-service
  namespace: besu
spec:
  type: LoadBalancer  # Exposes externally (for GCP)
  selector:
    app: besu
  ports:
    - name: rpc-http
      protocol: TCP
      port: 8545
      targetPort: 8545
    - name: rpc-ws
      protocol: TCP
      port: 8546
      targetPort: 8546
    - name: p2p
      protocol: TCP
      port: 30303
      targetPort: 30303