apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: besu
  namespace: besu
spec:
  serviceName: "besu"
  replicas: 1
  selector:
    matchLabels:
      app: besu
  template:
    metadata:
      labels:
        app: besu
    spec:
      containers:
      - name: besu
        image: hyperledger/besu:latest
        ports:
        - containerPort: 8545  # JSON-RPC HTTP
        - containerPort: 8546  # WebSockets
        - containerPort: 30303 # P2P communication
        args:
        - --network=dev
        - --rpc-http-enabled
        - --rpc-http-host=0.0.0.0
        - --rpc-http-api=ETH,NET,WEB3
        - --rpc-ws-enabled
        - --rpc-ws-host=0.0.0.0
        - --host-allowlist=*
        - --data-path=/var/lib/besu
        volumeMounts:
        - name: besu-data
          mountPath: /var/lib/besu
  volumeClaimTemplates:
  - metadata:
      name: besu-data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi