apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: besu
  namespace: besu
spec:
  serviceName: "besu"
  replicas: 1
  selector:
    matchLabels:
      app: besu
  template:
    metadata:
      labels:
        app: besu
    spec:
      containers:
      - name: besu
        image: hyperledger/besu:latest
        ports:
        - containerPort: 8545
        - containerPort: 8546
        - containerPort: 30303
        args:
        - --network=dev
        - --rpc-http-enabled
        - --rpc-http-host=0.0.0.0
        - --rpc-http-api=ETH,NET,WEB3
        - --rpc-ws-enabled
        - --rpc-ws-host=0.0.0.0
        - --host-allowlist=*